trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    steps:
    - bash: echo "Start Dev Deploy"
      strategy:
        runonce:
          deploy:
            steps:
            - script: echo deploy to dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    steps:
    - bash: echo "Start QA Deploy"
      strategy:
        runonce:
          deploy:
            steps:
            - script: echo deploy to QA
        

